Repository pulumi/pulumi-cloudflare, pull requests merged in 2019-06, with the labels that each got.

#12 Manage CHANGELOG with chg(1)
  CHANGELOG.md
Labels: enhancement

#13 Update pulumi-terraform to 7ace3e9b5f
  CHANGELOG.md
  go.mod
  go.sum
  sdk/nodejs/accessApplication.ts
  sdk/nodejs/accessPolicy.ts
  sdk/nodejs/accessRule.ts
  sdk/nodejs/accountMember.ts
  sdk/nodejs/argo.ts
  sdk/nodejs/customPages.ts
  sdk/nodejs/filter.ts
  sdk/nodejs/firewallRule.ts
  sdk/nodejs/loadBalancer.ts
  sdk/nodejs/loadBalancerMonitor.ts
  sdk/nodejs/loadBalancerPool.ts
  sdk/nodejs/logpushJob.ts
  sdk/nodejs/pageRule.ts
  sdk/nodejs/provider.ts
  sdk/nodejs/rateLimit.ts
  sdk/nodejs/record.ts
  sdk/nodejs/spectrumApplication.ts
  sdk/nodejs/wafRule.ts
  sdk/nodejs/workerRoute.ts
  sdk/nodejs/workerScript.ts
  sdk/nodejs/zone.ts
  sdk/nodejs/zoneLockdown.ts
  sdk/nodejs/zoneSettingsOverride.ts
Labels: area/providers

#14 Update to v1.16.0 of the Cloudflare Terraform provider
  CHANGELOG.md
  go.mod
  go.sum
  sdk/nodejs/pageRule.ts
  sdk/nodejs/zoneSettingsOverride.ts
Labels: enhancement

#16 Update pulumi-terraform to 3635bed3a5
  go.mod
  go.sum
  sdk/python/README.rst
Labels: area/providers

#17 Update .travis.yml to scripts
  .travis.yml
Labels: area/providers, impact/no-changelog-required

#18 Upgrade to v1.16.1 of the Cloudflare Terraform provider
  CHANGELOG.md
  go.mod
  go.sum
Labels: enhancement
